shopping:
  - type: movies
    items:
      - src: movies/2_guns
        title: 2 Guns
        info: Blu-ray
        price: $14.99

      - src: movies/avatar
        title: Avatar
        info:  3D Blu-ray
        price: $24.99

      - src: movies/brave
        title: Brave
        info: Blu-ray
        price: $24.99

      - src: movies/despicable_me_2
        title: Despicable Me 2
        info: Blu-ray
        price: $14.99

      - src: movies/gi_joe
        title: |
          G.I. Joe: Retaliation
        info: Blu-ray
        price: $14.99

      - src: movies/harry_potter
        title: | 
          Harry Potter: The Complete 8 Film Collection
        info: Blu-ray
        price: $54.99

      - src: movies/inception
        title: Inception
        info: Blu-ray
        price: $24.99

      - src: movies/iron_man_3
        title: Iron Man 3
        info: Blu-ray
        price: $24.99

      - src: movies/les_miserables
        title: Les Miserables
        info: Blu-ray
        price: $19.99

      - src: movies/man_of_steel
        title: Man of Steel
        info: Blu-ray
        price: $24.99

      - src: movies/monsters_university
        title: Monsters University
        info: Blu-ray
        price: $24.99

      - src: movies/pacific_rim
        title: Pacific Rim
        info: Blu-ray
        price: $24.99

      - src: movies/silver_linings_playbook
        title: Silver Linings Playbook
        info: Blu-ray
        price: $14.99

      - src: movies/skyfall
        title: Skyfall
        info: Blu-ray
        price: $24.99

      - src: movies/star_trek_into_darkness
        title: | 
          Star Trek: Into Darkness
        info: Blu-ray
        price: $29.99

      - src: movies/the_avengers
        title: The Avengers
        info: Blu-ray
        price: $24.99

      - src: movies/the_croods
        title: The Croods
        info: Blu-ray
        price: $14.99

      - src: movies/the_dark_knight_rises
        title: The Dark Knight Rises
        info: Blu-ray
        price: $14.99

      - src: movies/the_hobbit
        title: |
          The Hobbit: An Unexpected Journey
        info: Blu-ray
        price: $29.99

      - src: movies/the_hunger_games
        title: The Hunger Games
        info: Blu-ray
        price: $24.99

      - src: movies/the_little_mermaid
        title: The Little Mermaid
        info: Blu-ray
        price: $24.99

      - src: movies/the_wizard_of_oz
        title: The Wizard of Oz
        info: Blu-ray
        price: $14.99

      - src: movies/the_wolverine
        title: The Wolverine
        info: Blu-ray
        price: $24.99

      - src: movies/this_is_the_end
        title: This Is The End
        info: Blu-ray
        price: $14.99

      - src: movies/world_war_z
        title: World War Z
        info: Blu-ray
        price: $24.99
  - type: mobile
    items: 
      - src: mobile/droid_x
        title: Motorola Droid X
        info: 
        price: 

      - src: mobile/galaxy_s3
        title: Samsung Galaxy S3
        info: 
        price: 

      - src: mobile/galaxy_tab
        title: Samsung Galaxy Tab
        info: 
        price: 

      - src: mobile/htc_inspire
        title: HTC Inspire
        info: 
        price: 

      - src: mobile/htc_titan
        title: HTC Titan
        info: 
        price: 

      - src: mobile/ipad_mini
        title: Apple iPad Mini
        info: 
        price: 

      - src: mobile/iphone_4
        title: Apple iPhone 4
        info: 
        price: 

      - src: mobile/iphone_5c
        title: Apple iPhone 5C
        info: 
        price: 

      - src: mobile/iphone_5s
        title: Apple iPhone 5S
        info: 
        price: 

      - src: mobile/kindle_fire
        title: Kindle Fire
        info: 
        price: 

      - src: mobile/lumia_521
        title: Nokia Lumia 521
        info: 
        price: 

      - src: mobile/nexus_4
        title: Google Nexus 4
        info: 
        price: 

      - src: mobile/nexus_7
        title: Google Nexus 7
        info: 
        price: 
    - type: shoes
      items: 

      - src: shoes/womens_canvas_shoes
        title: Women's Canvas Shoes
        info:
        price:

      - src: shoes/vans
        title: Vans Sneakers
        info:
        price:

      - src: shoes/vans_red
        title: Vans Sneakers (Red)
        info:
        price:

      - src: shoes/sketchers_womens_slippers
        title: Sketchers Women's Slippers
        info:
        price:

      - src: shoes/sketchers_fusion_shoe
        title: Sketchers Fusion Shoes
        info:
        price:

      - src: shoes/rockport_wispen_mocc_toe
        title: Rockport Wispen Mocc Toe Shoe
        info:
        price:

      - src: shoes/rocket_dog_flats
        title: Rocket Dog Flats
        info:
        price:

      - src: shoes/qupid_high_heel_stiletto
        title: Qupid High Heel Stiletto
        info:
        price:

      - src: shoes/puma_osu_running_shoe
        title: Puma Osu Running Shoes
        info:
        price:

      - src: shoes/nine_west_pump
        title: Nine West Pumps
        info:
        price:

      - src: shoes/nine_west_boot
        title: Nine West Boots
        info:
        price:

      - src: shoes/nike_womens_revolution_running_shoe
        title: Nike Revolution Women's Running Shoes
        info:
        price:

      - src: shoes/nike_dart_running_shoe
        title: Nike Dart Running Shoes
        info:
        price:

      - src: shoes/madden_sneaker
        title: Madden Sneakers
        info:
        price:

      - src: shoes/dockers_gordon_cap_toe_oxford
        title: Dockers Gordon Cap Toe Oxford
        info:
        price:

      - src: shoes/crocs
        title: Crocs Classic Cog
        info:
        price:

      - src: shoes/converse_chuck_taylor
        title: Converse Chuck Taylor Sneakers
        info:
        price:

      - src: shoes/clarks_desert_boot
        title: Clark's Desert Boot
        info:
        price:

      - src: shoes/brixee_bootie
        title: Brixee Bootie
        info:
        price:

      - src: shoes/ASICS_running_shoe
        title: ASICS Running Shoe (Womens)
        info:
        price:
    - type: toys
      items: 

      - src: toys/barbie_collector_holiday
        title: Barbie Collector 2013 Holiday
        info:
        price:

      - src: toys/fischer-price_fun_sounds_farm
        title: Fischer-Price Fun Sounds Farm
        info:
        price:

      - src: toys/lego_coast_guard_patrol
        title: Lego Coast Guard Patrol
        info: 
        price:

      - src: toys/lincoln_logs
        title: Lincoln Logs
        info:
        price:

      - src: toys/magic_8_ball
        title: Magic 8 Ball
        info:
        price:

      - src: toys/monster_high_catty_noir
        title: Monster High Catty Noir Doll
        info:
        price:

      - src: toys/mr_potato_head
        title: Mr. Potato Head
        info:
        price:

      - src: toys/nerf_rebelle_heartbreaker
        title: Nerf Rebelle Heartbreaker
        info:
        price:

      - src: toys/nerf_strongarm_blaster
        title: Nerf Strongarm Blaster
        info:
        price:

      - src: toys/ninja_turtle_raphael
        title: Teenage Mutant Ninja Turtles Raphael
        info:
        price:

      - src: toys/play-doh
        title: Play-Doh Set
        info:
        price:

      - src: toys/rock_em_sock_em
        title: Rock 'em Sock 'em Robots
        info:
        price:

      - src: toys/settlers_of_catan
        title: Settlers of Catan
        info:
        price:

      - src: toys/simon
        title: Simon
        info: Memory Game
        price: $8.99

      - src: toys/lego_minecraft
        title: Lego Minecraft
        info:
        price:

downloads:
  - name: Mobile
    path: products/mobile
    images: 
      - droid_x
      - galaxy_s3
      - galaxy_tab
      - htc_inspire
      - htc_titan
      - ipad_mini
      - iphone_4
      - iphone_5c
      - iphone_5s
      - kindle_fire
      - lumia_521
      - nexus_4
      - nexus_7
  - name: Movies
    path: products/movies
    images:
      - 2_guns
      - avatar
      - brave
      - despicable_me_2
      - gi_joe
      - harry_potter
      - inception
      - iron_man_3
      - les_miserables
      - man_of_steel
      - monsters_university
      - pacific_rim
      - silver_linings_playbook
      - skyfall
      - star_trek_into_darkness
      - the_avengers
      - the_croods
      - the_dark_knight_rises
      - the_hobbit
      - the_hunger_games
      - the_little_mermaid
      - the_wizard_of_oz
      - the_wolverine
      - this_is_the_end
      - world_war_z
  - name: Toys
    path: products/toys
      - barbie_collector_holiday
      - fischer-price_fun_sounds_farm
      - lego_coast_guard_patrol
      - lego_minecraft
      - lincoln_logs
      - magic_8_ball
      - monster_high_catty_noir
      - mr_potato_head
      - nerf_rebelle_heartbreaker
      - nerf_strongarm_blaster
      - ninja_turtle_raphael
      - play-doh
      - rock_em_sock_em
      - settlers_of_catan
      - simon
  - name: Shoes
    path: products/shoes
      - ASICS_running_shoe
      - brixee_bootie
      - clarks_desert_boot
      - converse_chuck_taylor
      - crocs
      - dockers_gordon_cap_toe_oxford
      - madden_sneaker
      - nike_dart_running_shoe
      - nike_womens_revolution_running_shoe
      - nine_west_boot
      - nine_west_pump
      - puma_osu_running_shoe
      - qupid_high_heel_stiletto
      - rocket_dog_flats
      - rockport_wispen_mocc_toe
      - sketchers_fusion_shoe
      - sketchers_womens_slippers
      - vans
      - vans_red
      - womens_canvas_shoes
