id: 1
activities:
    - type: form
      instructions: Fill out the form for
      fields:
        first_name: John
        last_name: Smith
        street_1: 65 South Church St
        street_2: 
        city: Lancaster
        state: PA
        zip: 17601
        phone: 555-344-5682
        email: john_smith445@email.com

    - type: post
      instructions: Like the post where someone found some money.
      target: 3
      messages:
        - name: Susan Blanchett
          avatar: squirrel
          time: 5:21
          message: I just got a new puppy!  Very excited!

        - name: Jeremy Jones
          avatar: donkey
          time: 5:15
          message: Going to Las Vegas.  Hope I don't loose all my money lol.

        - name: John Smith
          avatar: chinchilla
          time: 4:45
          message: Just found $20 in my pocket while doing the laundry!

        - name: Harris Finch
          avatar: walrus
          time: 3:31
          message: Not looking forward to having to drive six hours.  Ugh.

    - type: shopping
      instructions: Add a 3D movie to the shopping cart.
      target: 1
      items:
        - src: movies/2_guns
          title: 2 Guns
          info: Blu-ray
          price: $24.99

        - src: movies/avatar
          title: Avatar
          info:  3D Blu-ray
          price: $24.99

        - src: movies/brave
          title: Brave
          info: Blu-ray
          price: $24.99

        - src: movies/despicable_me_2
          title: Despicable Me 2
          info: Blu-ray
          price: $24.99

        - src: movies/gi_joe
          title: |
            G.I. Joe: Retaliation
          info: Blu-ray
          price: $24.99

        - src: movies/harry_potter
          title: | 
            Harry Potter: The Complete 8 Film Collection
          info: Blu-ray
          price: $24.99

        - src: movies/inception
          title: Inception
          info: Blu-ray
          price: $24.99

        - src: movies/iron_man_3
          title: Iron Man 3
          info: Blu-ray
          price: $24.99

        - src: movies/les_miserables
          title: Les Miserables
          info: Blu-ray
          price: $24.99

        - src: movies/man_of_steel
          title: Man of Steel
          info: Blu-ray
          price: $24.99

        - src: movies/monsters_university
          title: Monsters University
          info: Blu-ray
          price: $24.99

        - src: movies/pacific_rim
          title: Pacific Rim
          info: Blu-ray
          price: $24.99

        - src: movies/silver_linings_playbook
          title: Silver Linings Playbook
          info: Blu-ray
          price: $24.99

        - src: movies/skyfall
          title: Skyfall
          info: Blu-ray
          price: $24.99

        - src: movies/star_trek_into_darkness
          title: | 
            Star Trek: Into Darkness
          info: Blu-ray
          price: $24.99

        - src: movies/the_avengers
          title: The Avengers
          info: Blu-ray
          price: $24.99

        - src: movies/the_croods
          title: The Croods
          info: Blu-ray
          price: $24.99

        - src: movies/the_dark_knight_rises
          title: The Dark Knight Rises
          info: Blu-ray
          price: $24.99

        - src: movies/the_hobbit
          title: |
            The Hobbit: An Unexpected Journey
          info: Blu-ray
          price: $24.99

        - src: movies/the_hunger_games
          title: The Hunger Games
          info: Blu-ray
          price: $24.99

        - src: movies/the_little_mermaid
          title: The Little Mermaid
          info: Blu-ray
          price: $24.99

        - src: movies/the_wizard_of_oz
          title: The Wizard of Oz
          info: Blu-ray
          price: $24.99

        - src: movies/the_wolverine
          title: The Wolverine
          info: Blu-ray
          price: $24.99

        - src: movies/this_is_the_end
          title: This Is The End
          info: Blu-ray
          price: $24.99

        - src: movies/world_war_z
          title: World War Z
          info: Blu-ray
          price: $24.99

    - type: download
      instructions: Click the image of the lastest iPhone to download it.
      target: iphone_5s
      categories:
        - name: Mobile
          path: products/mobile
          images: 
            - droid_x
            - galaxy_s3
            - iphone_5c
            - kindle_fire
            - nexus_4
            - htc_titan
            - iphone_5s
            - ipad_mini
        - name: Movies
          path: products/movies
          images:
            - harry_potter
            - les_miserables
            - pacific_rim
            - star_trek_into_darkness
            - the_dark_knight_rises
            - avatar
            - brave
            - despicable_me_2